[[constraint]]
name = "github.com/stellar/go"
branch = "master"

[[constraint]]
name = "github.com/lib/pq"
branch = "master"

[[constraint]]
name = "github.com/elastic/go-elasticsearch"
branch = "master"

[[constraint]]
name = "github.com/jmoiron/sqlx"
branch = "master"

[[constraint]]
name = "gopkg.in/alecthomas/kingpin.v2"
version = "v2"