version: 2.1

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: astrologer-k8s-deploy
          filters:
            branches:
              only:
                - master
      # - deployProductionGKE:
      #     context: ebaysocial-k8s-deploy
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - release
      #           - release-gke

# executors:
#   gcloud-helm:
#     docker:
#       - image: docker:18.09.8

jobs:
  build:
    docker:
      - image: docker:18.09.8
    steps:
      - checkout
      - setup_remote_docker

      # Login to Docker
      - run:
          name: Login to docker
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin

      # build the application image
      - run:
          name: Build docker image
          command: docker build -t astroband/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1} .

      # deploy the image
      - run:
          name: Push image to Google Container Registry
          command: docker push -t astroband/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}

  # deployTemplateGKE: &deployTemplateGKE
  #   executor: gcloud-helm

  #   steps:
  #     - checkout

  #     - run:
  #         name: Setup Google Cloud SDK
  #         command: |
  #           echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
  #           gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  #           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
  #           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  #           gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
  #     - deploy:
  #         command: /usr/local/bin/helm upgrade ${HELM_RELEASE} ./charts/items-api/  --reuse-values --set image.tag=${CIRCLE_BRANCH}-${CIRCLE_SHA1} --wait --atomic

  # deployProductionGKE:
  #   <<: *deployTemplateGKE
  #   environment:
  #     HELM_RELEASE: items-api      